version: '3.8'

services:
  web:
    build: .
    container_name: amopromo_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=amopromo_test.settings